language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 8

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

after_success: npm run coverage

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npm run semantic-release
